export interface CatchEntry {
  id: string;
  species: string;
  weight: string;
  length: string;
  location: string;
  waterType: string;
  weather: string;
  bait: string;
  date: string;
  notes: string;
  emoji: string;
}

// Backend integration point: replace with API fetch from /api/catches?memberId=current
export const initialCatches: CatchEntry[] = [
  {
    id: 'catch-047',
    species: 'Rainbow Trout',
    weight: '1.8 kg',
    length: '42 cm',
    location: 'Thredbo River',
    waterType: 'River',
    weather: 'Overcast',
    bait: 'Lure – spinner',
    date: '21 Apr 2026',
    notes: 'Caught near the falls pool at dawn. Released.',
    emoji: '🐟',
  },
  {
    id: 'catch-046',
    species: 'Murray Cod',
    weight: '3.4 kg',
    length: '61 cm',
    location: 'Murray River',
    waterType: 'River',
    weather: 'Sunny',
    bait: 'Live yabby',
    date: '14 Apr 2026',
    notes: 'Personal best! Took 15 minutes to land. Kept.',
    emoji: '🐠',
  },
  {
    id: 'catch-045',
    species: 'Yellowbelly',
    weight: '1.2 kg',
    length: '38 cm',
    location: 'Lake Hume',
    waterType: 'Lake',
    weather: 'Partly Cloudy',
    bait: 'Soft plastic',
    date: '14 Apr 2026',
    notes: 'Two bites before this one. Solid fight.',
    emoji: '🦈',
  },
  {
    id: 'catch-044',
    species: 'Flathead',
    weight: '0.9 kg',
    length: '34 cm',
    location: 'Port Phillip Bay',
    waterType: 'Sea',
    weather: 'Windy',
    bait: 'Soft plastic – prawn',
    date: '7 Apr 2026',
    notes: 'Wading at low tide. Three flathead in 2 hours.',
    emoji: '🐡',
  },
  {
    id: 'catch-043',
    species: 'Silver Perch',
    weight: '0.6 kg',
    length: '27 cm',
    location: 'Ovens River',
    waterType: 'River',
    weather: 'Sunny',
    bait: 'Worm',
    date: '31 Mar 2026',
    notes: 'First silver perch! Unlocked Species Hunter badge.',
    emoji: '🐟',
  },
  {
    id: 'catch-042',
    species: 'Brown Trout',
    weight: '2.1 kg',
    length: '48 cm',
    location: 'Mitta Mitta River',
    waterType: 'River',
    weather: 'Foggy',
    bait: 'Dry fly',
    date: '24 Mar 2026',
    notes: 'Dad helped with the fly cast. Amazing morning.',
    emoji: '🐟',
  },
  {
    id: 'catch-041',
    species: 'Redfin Perch',
    weight: '0.4 kg',
    length: '22 cm',
    location: 'Lake Eildon',
    waterType: 'Lake',
    weather: 'Clear',
    bait: 'Small spinner',
    date: '17 Mar 2026',
    notes: 'Lots of redfin schooling near the old jetty.',
    emoji: '🐠',
  },
  {
    id: 'catch-040',
    species: 'Australian Bass',
    weight: '1.5 kg',
    length: '36 cm',
    location: 'Snowy River',
    waterType: 'River',
    weather: 'Sunny',
    bait: 'Surface popper',
    date: '10 Mar 2026',
    notes: 'Hit the popper hard at dusk. Great fight.',
    emoji: '🦈',
  },
  {
    id: 'catch-039',
    species: 'Yellowfin Bream',
    weight: '0.7 kg',
    length: '29 cm',
    location: 'Gippsland Lakes',
    waterType: 'Lake',
    weather: 'Overcast',
    bait: 'Prawn',
    date: '3 Mar 2026',
    notes: 'Fished off the boat with Mum.',
    emoji: '🐡',
  },
  {
    id: 'catch-038',
    species: 'Rainbow Trout',
    weight: '1.1 kg',
    length: '35 cm',
    location: 'Howqua River',
    waterType: 'River',
    weather: 'Rainy',
    bait: 'Worm',
    date: '24 Feb 2026',
    notes: 'Rainy day but still got one. Rainbow number 3!',
    emoji: '🐟',
  },
  {
    id: 'catch-037',
    species: 'Cod',
    weight: '2.8 kg',
    length: '55 cm',
    location: 'Darling River',
    waterType: 'River',
    weather: 'Hot, 36°C',
    bait: 'Crayfish',
    date: '15 Feb 2026',
    notes: 'Summer trip with the club. Big cod in the shade.',
    emoji: '🐠',
  },
  {
    id: 'catch-036',
    species: 'Flathead',
    weight: '1.3 kg',
    length: '45 cm',
    location: 'Westernport Bay',
    waterType: 'Sea',
    weather: 'Calm',
    bait: 'Soft plastic',
    date: '8 Feb 2026',
    notes: 'Early morning session. Best flathead yet.',
    emoji: '🐡',
  },
];